### ISSUE TITLE
Solidify the interfaces and core definitions

### ISSUE THREAD

**Issue by gmalecha** [DeepSpec/InteractionTrees#31]
I opened a PR to note this in the README file. I think we should try to accelerate the process of stabilizing the interface, especially since projects such as Vellvm are already using the code here. I think the outstanding issues are.

- [x] Converting `itree` to a record. Issue #25 and PR #26.
- [ ] Compositional proof methodology. The current proposals are paco and PR #24. I know that paco needs a lot more exploration if we are going to use it effectively. #24 seems like it has a reasonable story but we should make sure that we understand it and port it to the record definition of itree. I'd like to propose that one way to know that we are done is to prove the `mfix_unfold` theorem inside the `Fix.v` file. That proof requires transitivity, reflexivity, bind associativity as well as theorems about `interp`.

It looks like there are already some comparison files, e.g. `IxEffects`, `Machines`, `CoAlgebra`. If they are only useful for experimenting between different representations, then they should be moved into a directory with a README and clear documentation on each file about what the experiment is about (with pointers to appropriate related work).

**Comment by Lysxia** [comment]
I agree `mfix_unfold` seems like a good target.

I moved the experimental files from `theories/` to `experiments/`.

**Comment by bollu** [comment]
I had a bunch of proofs that I was interested in which pushed the vellvm infrastructure:

- [A proof of a very limited form of store switching](https://github.com/bollu/vellvm/blob/master/src/coq/StoreSwitchProof.v#L756), that [pattern matches on the exact IR](https://github.com/bollu/vellvm/blob/master/src/coq/StoreSwitch.v#L84). 

Even though the pass was _very simple_, I had to write a bunch of tedious theorems about execution, memory, unwrapping.

I got stuck at some point when I had to reason about control flow - I was implementing a [pass that reverses a specific loop](https://github.com/bollu/vellvm/blob/master/src/coq/LoopReversalPass.v#L167). I'd attempted a proof, but reasoning about control flow was incredibly complex for me [(LINK)](https://github.com/bollu/vellvm/blob/master/src/coq/LoopReversalManualProof.v)

While I understand that this isn't directly related to `InteractionTrees`, I'd like to understand what kind of experiments would be valuable to `InteractionTrees`, so I can try things out and report back as a consumer :)

Thanks!

**Comment by bollu** [comment]
@gmalecha Indeed, having the `Trace` structure be nice to interact with would be great. The problems that I had faced when reasoning about `Trace` were:

- Lack of instances of `Proper` to enable easy rewriting.
- Lemmas such as this one (I'm sorry, I'm going to dump lemmas I had to write, because it might be easier for you to cross-check than for me to go spelunk in the PR)

```coq
Lemma bindM_proper_wrt_eutt:
  forall {A B: Type} {E: Type -> Type} (a a': M E A) (f: A -> M E B),
    a ≡ a' -> bindM a f ≡ bindM a' f.

```
```coq
Lemma bindM_extensionality: 
  forall {E: Type -> Type } {X Y: Type} (f g: X -> M E Y)
  (EXT: forall (x: X), f x ≡ g x) (ex: M E X), bindM ex f ≡ bindM ex g.

```
- some kind of hint database to simplify monadic expressions around `Trace` that re-associates binds, and "deconstructs" the trace: [LINK HERE](https://github.com/bollu/vellvm/blob/master/src/coq/Trace.v#L1548)

- facts about "splicing" finite traces / some way to reason about a finite part of a trace. This is useful to be able to write proofs about a section of the Trace --- ([LINK HERE](https://github.com/bollu/vellvm/blob/master/src/coq/Memory.v#L762))

```coq
Theorem memD_commutes_with_bind_fin: forall {X Y: Type}
                                 (trx: Trace X)
                                 (FINTRX: Trace.TraceFinite trx)
                                 (f: X -> Trace Y)
                                 (m: memory),
    let (m', trx') := mem_effect_fin m FINTRX
    in memD m (bindM trx f) ≡
            memD m' (bindM trx' f).
```

- The ability to prove facts about memory, such as [this one (LINK)](https://github.com/bollu/vellvm/blob/master/src/coq/Memory.v#L956)

```coq
Theorem memEffect_commutes_with_bind: forall {X Y: Type}
                                        (trx: Trace X)
                                        (f: X -> Trace Y)
                                        (m: memory),
    memEffect m (bindM trx f) ≡
              bindM (memEffect m trx)
              (fun out: memory * X => memEffect (fst out) (f (snd out))).
```

I'm writing much of this from memory, and I haven't actively played around with this --- If this is the wrong medium to discuss these concerns, I apologise, and I can drop a mail if that works.

Thanks,
~Siddharth

**Comment by bollu** [comment]
I wasn't sure if the constructs I listed were defined in `InteractionTrees` yet -- thanks for clarifying that they are.

**Comment by Lysxia** [comment]
With the latest reorganization #93 (summarized in the [README, Organization section](https://github.com/DeepSpec/InteractionTrees/blob/5be1bf3d57d5c4d83c8e5dd4716e821f285cf783/README.md)) we can say the interface is pretty solid now.
