### ISSUE TITLE
Too much type class inference, use handler combinators instead

### ISSUE THREAD

**Issue by gmalecha** [DeepSpec/InteractionTrees#63]
Last night, we had a lot of difficulty with type-class resolution resolving to strange things. I think it would be good to have most of the core definitions be opt-in on type classes.

In addition to avoiding type-class bugs, this might also lead us to a set of lemmas that we can use to reason about effect morphisms.

**Comment by Zdancewic** [comment]
Was this mostly having to do with the subeffect typeclases?   I think that the `E -< F` typeclass constraints aren't working as we'd like them to, especially if you try to mix them with explicit sum1's.  

 I think that maybe part of the issue is that the open sums aren't quite providing the correct notion of subeffect.  In particular, we can show `A +' A -< A` but that doesn't line up with (at least my intuition) about the way that interpeters should work:  if we have `stateE S +' stateE S` we want to have two independent state monads, we don't (typically) want the itree to be coercible to one that is interpretable in a single state monad.

**Comment by gmalecha** [comment]
Yes, this is exactly right. I think the right thing to do is to just use something like `interp` that interprets the entire effect into another effect. Then people can use categorical combinators for composing effect handlers.

**Comment by gmalecha** [comment]
We struggled with this a little bit during the compiler proof today. The inference can also make it more complex to reason about the resulting code because the "location" of the effects is implicit. For clarity on the proposal, I'm thinking of something like the following (ignoring the `itree` on the right of `~>`):

```coq
(* category *)
id : A ~> A
compose : (B ~> C) ~> (A ~> B) -> (A ~> C)
(* co-cartesian *)
par : (A ~> B) -> (C ~> D) -> (A + C ~> B + D)
both : (A ~> B) -> (C ~> B) -> (A + C ~> B)
left : A ~> A + B
right : B ~> A + B
```
These should obey all the standard categorical laws and we should be able to prove some generic laws about how they interact with `interp` and `lift` which should be useful for writing some generic automation. The downside is that we have to write them for all of the different monads, but we seem to have to do that anyways.

**Comment by Zdancewic** [comment]
It might be slightly cleaner to take:
```
left : (A ~> B) -> (A ~> B + C)
right : (C ~> D) -> (C ~> A + D)
```
Then `par f g = both (left f) (right g)` and `swap f g = both (right f) (left g)`.

However, there are two layers going on here.  The above category works until we try to give interesting interpretations to the effects, in which case I wonder whether we should be thinking more in terms of monad transformers, rather than monads.  That is, rather than thinking of the category as having morphisms of the form `A ~> (itree B)`, we work with morphisms of the form `A ~> T (itree B)` where `T` is a monad transformer applied to `(itree B)`.  The laws above all hold for `T = ID`, the identity monad transformer, but not for other `T`'s.  

I've found the following paper to be very enlightening:
[Monad Transformers and Modular Algebraic Effects: What Binds Them Together](http://www.cs.kuleuven.be/publicaties/rapporten/cw/CW699.pdf)

**Comment by Lysxia** [comment]
`interp1` is going away for now. The handler interface needs a bit of polishing. We have three or four monoidal categories going on here, it would be nice if they all use the same names (we're slowly getting there).

We could even use type classes or canonical structure to unify them further, but I'm worried about unfolding in proofs. Even with `Monad` for example, we could state laws like `bind_bind` in terms of it, but as soon as you do a `simpl.` the class goes away and you can't rewrite anything anymore. How to deal with this?

Otherwise we can use modules and force identifiers to be qualified by default (like we do with `ITree.bind` for example), allowing one to import heavily used modules as needed.

**Comment by Lysxia** [comment]
The original problem here was with `interp1` using the `Subeffect` class. Now we have only `interp` and handler combinators (or explicit handlers, possibly using `send`, which depends on `Subeffect`, but that seems more manageable). There might be other problems because the handler combinators are also defined using type classes so it's sometimes ambiguous whether to use the `IFun` or `Handler` categories, but let's consider that a different issue.

We'll also revisit Steve's comments about monad transformers as part of figuring out the full story behind `interp`/`aloop`.
